apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-fitness-app
  namespace: default
spec:
  provider: azure
  secretObjects:
  # This section creates a regular Kubernetes Secret from the Key Vault data
  # so that the Pod can load it into environment variables easily.
  - secretName: fitness-app-env-secret
    type: Opaque
    data:
    # 'objectName' must match the secret name in Key Vault
    # 'key' will be the name of the environment variable in Kubernetes
    - objectName: MONGODB-URI
      key: MONGODB_URI
    - objectName: JWT-SECRET
      key: JWT_SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "4c95ba24-b01d-4336-a133-3b81037acd78" # Replace with your Client ID
    keyvaultName: "Fit-kv1" # Replace with your Key Vault name
    tenantId: "01ed7ca4-f203-43a5-956a-08329f95a438" # You can get this by running: az account show --query tenantId -otsv
    objects: |
      array:
        - |
          objectName: MONGODB-URI
          objectType: secret
          objectVersion: ""
        - |
          objectName: JWT-SECRET
          objectType: secret
          objectVersion: ""
